FROM node:17-alpine AS builder

WORKDIR /frontend
COPY . /frontend

RUN npm install

ENV PATH ./node_modules/.bin:$PATH

RUN npm run build

FROM nginx:1.21.6-alpine
RUN apk --no-cache add curl
RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst && \
    chmod +x envsubst && \
    mv envsubst /usr/local/bin
COPY ./nginx.config /etc/nginx/nginx.template
CMD ["/bin/sh", "-c", "envsubst < /etc/nginx/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
COPY --from=builder /frontend/build /usr/share/nginx/html
