FROM python:3

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DEBUG 0

COPY . .

RUN pip install -r backend/requirements.txt

CMD python backend/manage.py makemigrations && \
    python backend/manage.py migrate && \
    python backend/manage.py runserver 0.0.0.0:8000
