FROM python:3

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DEBUG 0

COPY . .

WORKDIR /backend

RUN ls

RUN pip install -U pip && \
    pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev

CMD poetry run python manage.py makemigrations && \
    poetry run python manage.py migrate && \
    gunicorn -b 0.0.0.0:8000 --worker-class=gevent --worker-connections=1000 --workers=5 backend.wsgi
